version: '3.8'
services:
    app:
        build: .
        container_name: rest_service
        restart: always
        env_file: .env
        networks:
            - rest_network
        volumes:
            - .:/app
        ports:
            - '${PORT}:${PORT}'

    db:
        image: postgres:13-alpine
        container_name: postgres_db
        restart: always
        env_file: .env
        networks:
            - rest_network
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - postgres_logs:/var/log/postgresql
        ports:
            - '${DB_PORT}:${DB_PORT}'

networks:
    rest_network:
        driver: ${NETWORK_DRIVER}

volumes:
    postgres_data:
    postgres_logs:
