replicaCount: 1

image:
  repository: 287703574697.dkr.ecr.us-east-1.amazonaws.com/rest-api-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 4000

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
